Start using 'docker compose' instead of docker-compose
Recent upgrade left me with error when trying to redeploy:

KeyError: 'ContainerConfig'

See https://stackoverflow.com/a/78225629/11827
and https://docs.docker.com/compose/migrate/